from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from . import api
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^favicon\.ico$',RedirectView.as_view(url=r'static/favicon.ico')),
    url(r'^api/ajax_list/$', api.ajax_list),
    url(r'^api/ajax_dict/$', api.ajax_dict),
    url(r'^api/addname/$', api.addname),
    url(r'^api/getname/$', api.getname),
    url(r'^api/addplaintext/$', api.addplaintext),
    url(r'^api/getplaintext/$', api.getplaintext),
    url(r'^api/uploadfile/$', api.uploadfile),
    url(r'^api/downloadfile/$', api.downloadfile),
    url(r'^api/sendemail/$', api.sendemail),
    url(r'^api/createuser/$', api.createuser),
    url(r'^api/login/$', api.login),
    url(r'^api/changepassword/$', api.changepassword),
    url(r'^api/showpersonalintro/$', api.show_personalintro),         
    url(r'^api/changepersonalintro/$', api.change_personalintro),  
    url(r'^api/showpersonaldoc/$',api.show_personal_doc),         
    url(r'^api/changepersonaldoc/$',api.change_personal_doc),    
    url(r'^api/addpersonaldoc/$',api.add_personal_doc),
    url(r'^api/creategroup/$',api.create_group),
    url(r'^api/addgroupdoc/$',api.add_group_doc),
    url(r'^api/deletepersonaldoc/$',api.delete_personal_doc),  
    url(r'^api/deleteallpersonaldoc/$',api.delete_all_personal_doc), 
    url(r'^api/deletegroupdoc/$',api.delete_group_doc),
    url(r'^api/takedoctorecycle/$',api.take_doc_to_recycle),
    url(r'^api/recoverfromrecycle/$',api.recover_from_recycle),
    url(r'^api/showpersonaldoclist/$',api.show_personal_doclist),
    url(r'^api/showrecycledoclist/$',api.show_recycle_doclist),
    url(r'^api/showfavoritedoclist/$',api.show_favorite_doclist),
    url(r'^api/showgroupdoclist/$',api.show_group_doclist),
    url(r'^api/leavegroup/$',api.leave_group),
    url(r'^api/dismissgroup/$',api.dismiss_group),
    url(r'^api/joingroup/$',api.join_group),                           
    url(r'^api/showgrouplist/$',api.show_grouplist),
    url(r'^api/addfavoritedoc/$',api.add_favorite_doc),
    url(r'^api/deletegroupmember/$',api.delete_group_member),
    url(r'^api/add_comment/$',api.add_comment),
    url(r'^api/returndemo/$',api.return_demo),
    url(r'^api/latestbrowse/$',api.latest_browse),
    url(r'^api/removefavoritedoc/$',api.remove_favorite_doc),
    url(r'^api/showgroupmemberlist/$',api.show_groupmember_list),
    url(r'^api/show_comment/$',api.show_comment),
    url(r'^api/del_comment/$',api.del_comment),
    url(r'^api/newgroupdoc/$', api.new_group_doc),
    url(r'^api/sendverifycode/$', api.sendverifycode),
    url(r'^api/addbackgroundphoto/$', api.addbackgroundphoto),
    url(r'^api/addprofilephoto/$', api.addprofilephoto),
    url(r'^api/showbackgroundphoto/$', api.showbackgroundphoto),
    url(r'^api/showprofilephoto/$', api.showprofilephoto),
    url(r'^api/getsystemmessage/$', api.getsystemmessage),
    url(r'^api/getteammessage/$', api.getteammessage),
    url(r'^api/getdocumentmessage/$', api.getdocumentmessage),
    url(r'^api/changeauthority/$', api.changeauthority),
    url(r'^api/checkauthority/$', api.check_authority),
    url(r'^api/returnusername/$', api.return_user_name),
    url(r'^api/invite/$', api.invite),
    url(r'^api/receiveinvitation/$', api.receive_invitation),
    url(r'^api/accept/$', api.accept),
    url(r'^api/ignore/$', api.ignore),
    url(r'^api/showgroupintro/$', api.showgroupintro),
    url(r'^api/changegroupintro/$', api.changegroupintro),
    url(r'^api/lockdoc/$', api.lock_doc),
    url(r'^api/returnlockstatus/$', api.return_lock_status),
    url(r'^api/unlock/$', api.unlock),
    url(r'^api/showalterhistory/$', api.show_alterhistory),
    url(r'^api/getlock/$', api.getlock),
    url(r'^admin/', admin.site.urls),
    url(r'^', TemplateView.as_view(template_name="index.html")),
]
