# -*- coding: utf-8 -*-
import scrapy
import json
import countrydaylist.items as ci


class CdlspiderSpider(scrapy.Spider):
    name = "cdlspider"
    allowed_domains = ["news.qq.com"]
    start_urls = 'https://api.inews.qq.com/newsqa/v1/automation/foreign/daily/list'

    def start_requests(self):
        data = [
            {'country': "美国"},
            {'country': "印度"},
            {'country': "巴西"},
            {'country': "法国"},
            {'country': "俄罗斯"},
            {'country': "土耳其"},
            {'country': "英国"},
            {'country': "阿根廷"},
            {'country': "哥伦比亚"},
            {'country': "意大利"},
            {'country': "西班牙"},
            {'country': "德国"},
            {'country': "伊朗"},
            {'country': "波兰"},
            {'country': "墨西哥"},
            {'country': "乌克兰"},
            {'country': "印度尼西亚"},
            {'country': "秘鲁"},
            {'country': "南非"},
            {'country': "荷兰"},
            {'country': "捷克"},
            {'country': "智利"},
            {'country': "菲律宾"},
            {'country': "加拿大"},
            {'country': "伊拉克"},
            {'country': "瑞典"},
            {'country': "比利时"},
            {'country': "罗马尼亚"},
            {'country': "巴基斯坦"},
            {'country': "孟加拉"},
            {'country': "葡萄牙"},
            {'country': "以色列"},
            {'country': "匈牙利"},
            {'country': "日本本土"},
            {'country': "马来西亚"},
            {'country': "约旦"},
            {'country': "塞尔维亚"},
            {'country': "瑞士"},
            {'country': "奥地利"},
            {'country': "尼泊尔"},
            {'country': "阿联酋"},
            {'country': "黎巴嫩"},
            {'country': "摩洛哥"},
            {'country': "沙特阿拉伯"},
            {'country': "哈萨克斯坦"},
            {'country': "厄瓜多尔"},
            {'country': "玻利维亚"},
            {'country': "突尼斯"},
            {'country': "巴拉圭"},
            {'country': "希腊"},
            {'country': "保加利亚"},
            {'country': "白俄罗斯"},
            {'country': "巴拿马"},
            {'country': "斯洛伐克"},
            {'country': "乌拉圭"},
            {'country': "哥斯达黎加"},
            {'country': "格鲁吉亚"},
            {'country': "科威特"},
            {'country': "克罗地亚"},
            {'country': "阿塞拜疆"},
            {'country': "多米尼加"},
            {'country': "巴勒斯坦"},
            {'country': "危地马拉"},
            {'country': "丹麦"},
            {'country': "泰国"},
            {'country': "埃及"},
            {'country': "立陶宛"},
            {'country': "埃塞俄比亚"},
            {'country': "委内瑞拉"},
            {'country': "阿曼"},
            {'country': "爱尔兰"},
            {'country': "洪都拉斯"},
            {'country': "巴林"},
            {'country': "斯里兰卡"},
            {'country': "斯洛文尼亚"},
            {'country': "摩尔多瓦"},
            {'country': "亚美尼亚"},
            {'country': "卡塔尔"},
            {'country': "波黑"},
            {'country': "古巴"},
            {'country': "利比亚"},
            {'country': "肯尼亚"},
            {'country': "尼日利亚"},
            {'country': "缅甸"},
            {'country': "赞比亚"},
            {'country': "韩国"},
            {'country': "北马其顿"},
            {'country': "阿尔及利亚"},
            {'country': "拉脱维亚"},
            {'country': "阿尔巴尼亚"},
            {'country': "挪威"},
            {'country': "爱沙尼亚"},
            {'country': "吉尔吉斯斯坦"},
            {'country': "蒙古"},
            {'country': "阿富汗"},
            {'country': "乌兹别克斯坦"},
            {'country': "黑山"},
            {'country': "芬兰"},
            {'country': "加纳"},
            {'country': "纳米比亚"},
            {'country': "乌干达"},
            {'country': "喀麦隆"},
            {'country': "莫桑比克"},
            {'country': "萨尔瓦多"},
            {'country': "塞浦路斯"},
            {'country': "马尔代夫"},
            {'country': "博茨瓦纳"},
            {'country': "卢森堡"},
            {'country': "新加坡"},
            {'country': "津巴布韦"},
            {'country': "柬埔寨"},
            {'country': "牙买加"},
            {'country': "科特迪瓦"},
            {'country': "塞内加尔"},
            {'country': "卢旺达"},
            {'country': "马达加斯加"},
            {'country': "刚果（金）"},
            {'country': "安哥拉"},
            {'country': "马拉维"},
            {'country': "苏丹"},
            {'country': "特立尼达和多巴哥"},
            {'country': "佛得角"},
            {'country': "澳大利亚"},
            {'country': "马耳他"},
            {'country': "叙利亚"},
            {'country': "加蓬"},
            {'country': "几内亚"},
            {'country': "苏里南"},
            {'country': "毛里塔尼亚"},
            {'country': "圭亚那"},
            {'country': "越南"},
            {'country': "斯威士兰"},
            {'country': "海地"},
            {'country': "巴布亚新几内亚"},
            {'country': "塞舌尔"},
            {'country': "索马里"},
            {'country': "马里"},
            {'country': "多哥"},
            {'country': "安道尔"},
            {'country': "塔吉克斯坦"},
            {'country': "布基纳法索"},
            {'country': "伯利兹"},
            {'country': "巴哈马"},
            {'country': "刚果（布）"},
            {'country': "吉布提"},
            {'country': "莱索托"},
            {'country': "东帝汶"},
            {'country': "赤道几内亚"},
            {'country': "贝宁"},
            {'country': "尼加拉瓜"},
            {'country': "中非共和国"},
            {'country': "也门"},
            {'country': "冰岛"},
            {'country': "斐济"},
            {'country': "冈比亚"},
            {'country': "厄立特里亚"},
            {'country': "塞拉利昂"},
            {'country': "尼日尔"},
            {'country': "布隆迪"},
            {'country': "圣卢西亚"},
            {'country': "圣马力诺"},
            {'country': "乍得"},
            {'country': "利比里亚"},
            {'country': "巴巴多斯"},
            {'country': "科摩罗"},
            {'country': "几内亚比绍"},
            {'country': "列支敦士登公国"},
            {'country': "新西兰"},
            {'country': "摩纳哥"},
            {'country': "老挝"},
            {'country': "圣文森特和格林纳丁斯"},
            {'country': "不丹"},
            {'country': "毛里求斯"},
            {'country': "安提瓜和巴布达"},
            {'country': "钻石号邮轮"},
            {'country': "坦桑尼亚"},
            {'country': "圣基茨和尼维斯"},
            {'country': "文莱"},
            {'country': "多米尼克"},
            {'country': "格林纳达"},
            {'country': "马提尼克岛"},
            {'country': "梵蒂冈"},
            {'country': "所罗门群岛"},
            {'country': "瓦努阿图"},
            {'country': "马绍尔群岛"},
        ]

        for country in data:
            yield scrapy.FormRequest(url=self.start_urls, formdata=country,
                                     callback=lambda response, name=country['country']: self.parse(response, name))

    def parse(self, response, name):
        result = json.loads(response.text)['data']
        list = result[len(result) - 2: len(result)]
        for children in list:
            item = ci.CountrydaylistItem()
            item['date'] = children['date']
            item['name'] = name
            item['y'] = children['y']
            item['confirm'] = children['confirm']
            item['confirmAdd'] = children['confirm_add']
            item['heal'] = children['heal']
            item['dead'] = children['dead']
            # print(item)
            yield item
